org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2024.07.28
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mod_id=blastfromthepast
# The human-readable display name for the mod.
mod_name=Blast From The Past
mod_license=All Rights Reserved
mod_version=1.0.3
mod_group_id=team.recrafted.blast_from_the_past
mod_authors=Team Recrafted, Zigy, Clonz, Tenebris Mors
mod_description=B

#Dependencies
geckolib_version=4.7.4

mapping_version=1.20.1
mapping_channel=official
